-- nba_api.stats.static.teams не возвращает conference;
-- при загрузке через load_data.py конференция берётся из TEAM_CONFERENCE.

UPDATE teams SET conference = 'East' WHERE abbreviation = 'ATL';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'BOS';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'BKN';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'CHA';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'CHI';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'CLE';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'DAL';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'DEN';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'DET';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'GSW';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'HOU';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'IND';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'LAC';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'LAL';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'MEM';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'MIA';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'MIL';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'MIN';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'NOP';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'NYK';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'OKC';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'ORL';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'PHI';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'PHX';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'POR';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'SAC';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'SAS';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'TOR';
UPDATE teams SET conference = 'West' WHERE abbreviation = 'UTA';
UPDATE teams SET conference = 'East' WHERE abbreviation = 'WAS';
