@startuml relational_schema
hide circle
skinparam linetype ortho
skinparam defaultFontSize 14
skinparam shadowing false
skinparam roundcorner 5

' Увеличиваем расстояние между элементами
skinparam nodesep 80
skinparam ranksep 80

skinparam class {
  BackgroundColor White
  BorderColor Black
  ArrowColor Black
}

entity "positions" {
  + position_id PK
  --
  code UQ
  name
}

entity "seasons" {
  + season_id PK
  --
  label UQ
  start_date
  end_date
  season_type
}

entity "teams" {
  + team_id PK
  --
  nba_team_id UQ
  name UQ
  abbreviation UQ
  city
  conference
  arena_name
  founded_year
  is_active
}

entity "players" {
  + player_id PK
  --
  position_id FK
  nba_id UQ
  first_name
  last_name
  birth_date
  nationality
  height_cm
  weight_kg
  jersey_number
  draft_year
  draft_round
  draft_pick
  is_active
}

entity "games" {
  + game_id PK
  --
  season_id FK
  home_team_id FK
  away_team_id FK
  game_date
  home_score
  away_score
  status
  overtime
}

entity "game_player_stats" {
  + stat_id PK
  --
  game_id FK
  player_id FK
  team_id FK
  minutes_played
  points
  rebounds_off
  rebounds_def
  assists
  steals
  blocks
  turnovers
  fouls
  fgm
  fga
  fg3m
  fg3a
  ftm
  fta
  plus_minus
  is_starter
}

entity "player_season_stats" {
  + pss_id PK
  --
  player_id FK
  season_id FK
  team_id FK
  games_played
  avg_pts
  avg_reb
  avg_ast
  avg_stl
  avg_blk
  avg_tov
  avg_min
  avg_plus_minus
  fg_pct
  fg3_pct
  ft_pct
  efg_pct
  ts_pct
  usg_pct
  per
  bpm
}

entity "player_team_history" {
  + history_id PK
  --
  player_id FK
  team_id FK
  season_id FK
  start_date
  end_date
  contract_type
}

' Явно задаем горизонтальное направление (вправо) для основных цепочек таблиц
positions ||-right-o{ players : ""
players ||-right-o{ player_team_history : ""
players ||-down-o{ game_player_stats : ""
players ||-down-o{ player_season_stats : ""

teams ||-right-o{ games : ""
teams ||-right-o{ games : ""
teams ||-down-o{ game_player_stats : ""
teams ||-down-o{ player_season_stats : ""
teams ||-down-o{ player_team_history : ""

seasons ||-right-o{ games : ""
seasons ||-down-o{ player_season_stats : ""
seasons ||-down-o{ player_team_history : ""
games ||-down-o{ game_player_stats : ""

@enduml
